bldr:
    name: wouterj/site
    profiles:
        publish:
            description: Building and publishing the website
            tasks:
                - sass_generate
                - sculpin_generate
                - publish
        watch:
            description: Executes the watch commands
            tasks:
                - sass_watch
                - sculpin_watch
    tasks:
        sass_generate:
            description: Creates the css file
            calls:
                -
                    type: exec
                    executable: sass
                    arguments:
                        - 'source/css/wouterj.scss:source/css/wouterj.css'
                        - '--style'
                        - 'compressed'
                        - '--no-cache'

        sass_watch:
            description: Creates the css file and watches for changes
            calls:
                -
                    type: background
                    executable: sass
                    arguments:
                        - 'source/css/wouterj.scss:source/css/wouterj.css'
                        - '--watch'

        sculpin_generate:
            description: Creates the static website using Sculpin
            calls:
                -
                    type: exec
                    executable: vendor/bin/sculpin
                    arguments:
                        - 'generate'
                        - '--env'
                        - 'prod'

        sculpin_watch:
            description: Creates the static website using Sculpin and watches for changes
            calls:
                -
                    type: background
                    executable: vendor/bin/sculpin
                    arguments:
                        - 'generate'
                        - '--watch'
                        - '--server'

        publish:
            description: Publishes the output_prod directory to the master branch
            calls:
                -
                    type: exec
                    executable: sh
                    arguments: ['publish.sh']
