language: php
php:
- hhvm

before_script:
- gem install sass
- composer selfupdate
- composer install

script:
- vendor/bin/bldr build publish

env:
  global:
    secure: "HgMClXh/2I6IyqAdqg9uew1SBpwRb7Pxpu3T6x86HqqxY9L0YSP9wMQLWnPshiYcnJLQ5Qoth5wJCFSYSdmdrXOyzn83GHfrErFKhh8zpqZdLdg3aNEfo9l71KD6/lOhlyNn3wNowMguRH+g3APdgiVtQVc9KFBsDvrJDh47y4U="
