# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Wouter J
slogan: A script is more than just code
language: en
nav:
  - title: Home
    path: /
#  - title: Over mij
#    path: /about
  - title: Archive
    path: /archive
author: Wouter de Jong
